import { useState, useEffect } from 'react';
import PageTemplate from './PageTemplate';
import { Bell, ArrowRight } from 'lucide-react';

export default function Recommendations() {
  const [data, setData] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchRecs() {
      try {
        const token = localStorage.getItem('wealth-token');
        const res = await fetch('http://localhost:5000/api/advisor/recommendations', {
          headers: { 'Authorization': `Bearer ${token}` }
        });
        const data = await res.json();
        if (data.success) {
          setData(data.recommendations || []);
        }
      } catch (err) {
        console.error(err);
      } finally {
        setLoading(false);
      }
    }
    fetchRecs();
  }, []);

  return (
    <PageTemplate
      title="Investment Recommendations"
      subtitle="Dynamic rebalancing advice generated by asset mix discrepancy engines."
      details={[
        'Review automated asset rebalancing triggers based on allocation variances',
        'Dispatch recommendations to relationship managers or directly to client portals',
        'Track recommendation acceptance metrics and historical advisory runs',
        'Calibrate discrepancy thresholds to filter micro-allocation variances'
      ]}
    >
      {loading ? (
        <div className="flex justify-center py-12">
          <div className="animate-spin rounded-full h-8 w-8 border-t-2 border-b-2 border-emerald-500"></div>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-8">
          {data.map((item, idx) => (
            <div key={idx} className="bg-gray-900 border border-gray-800 rounded-2xl p-6 flex flex-col justify-between hover:border-emerald-500/30 transition-all duration-300">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-mono uppercase tracking-wider text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-md border border-emerald-500/20">
                    Active Advice
                  </span>
                  <Bell className="text-gray-600" size={16} />
                </div>
                <div>
                  <h4 className="text-xs font-semibold text-gray-400 font-mono uppercase">Investor Account</h4>
                  <p className="text-sm font-bold text-gray-200 mt-1">{item.investor_name}</p>
                </div>
                <div>
                  <h4 className="text-xs font-semibold text-gray-400 font-mono uppercase">Advisory Strategy</h4>
                  <p className="text-xs text-gray-300 leading-relaxed mt-1.5 p-3 bg-gray-950 rounded-xl border border-gray-850">
                    {item.recommendation}
                  </p>
                </div>
              </div>
              <button className="w-full mt-6 py-2.5 bg-emerald-500 hover:bg-emerald-400 text-slate-950 text-xs font-bold rounded-xl transition flex items-center justify-center gap-1.5">
                Dispatch Guidance <ArrowRight size={14} />
              </button>
            </div>
          ))}
          {data.length === 0 && (
            <div className="col-span-2 bg-gray-900 border border-gray-800 rounded-2xl p-12 text-center text-xs text-slate-500">
              No active investment recommendations available.
            </div>
          )}
        </div>
      )}
    </PageTemplate>
  );
}
